# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

jobs:
  build:
    steps:
      - checkout
      - run:
        name: Install Dependencies
        command: npm install
      - run:
        name: Build the application
        command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - package.json
            - node_modules
            - src
            - dist
  deploy-production:
    steps:
      - attach_workspace:
        at: ./
      - run:
        name: Deploy the application

workflows:  
  build-and-deploy:
    jobs:
      - build
      - deploy-production:
        requires:
          - build
        filters:
          branches:
            only:
              - master