version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
  cypress: cypress-io/cypress@1.26.0
defaults: &defaults
  docker:
    - image: circleci/node:12
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd hello-world && npm install
      - persist_to_workspace:
          root: ~/
          paths:
            - .
  deploy-production:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Build the application
          command: cd hello-world && npm run build
      - aws-s3/sync:
          from: 'hello-world/dist'
          to: 's3://simple-vue-cdk-app'
          overwrite: true
      - run: exit 0

workflows:  
  cypress-integration:
    jobs:
      - build
      - cypress/install:
          build: 'npm run build' # run a custom app build step
      - cypress/run: 
          requires:
            - "cypress/install"
  build-and-deploy:
    jobs:
      - build
      - deploy-production:
          context: circlecis3  
          requires:
              - build
          filters:
            branches:
              only:
                - master